<?php

//$Id: userpoints_basic.module,v 1.3.2.5.2.6 2007-12-07 15:06:34 jredding Exp $

// Copyright 2005 Khalid Baheyeldin http://2bits.com

define('USERPOINTS_POST',                'userpoints_post_');
define('USERPOINTS_POST_COMMENT',        'userpoints_post_comment');
define('USERPOINTS_MODERATE_COMMENT',    'userpoints_moderate_comment');

function userpoints_basic_help($section) {
  switch ($section) {
    case 'admin/settings/userpoints_basic':
      $output = t('<strong>UP:</strong> Some basic interfaces for userpoints, such as posting nodes, comments, ...etc.');
      break;
  }
  return $output;
}

function userpoints_basic_userpoints($op, $points = 0, $uid = 0, $event = '') {
  switch($op) {
    case 'setting':
      $group = 'basic';
      $form[$group] = array(
        '#type'        => 'fieldset',
        '#collapsible' => TRUE,
        '#collapsed'   => TRUE,
        '#title'       => t('!Points for basic events', userpoints_translation()),
      );
      
      foreach(node_get_types() as $type => $name) {
        $form[$group][USERPOINTS_POST. $type] = array(
          '#type'          => 'textfield',
          '#title'         => t('!Points for posting a !node-name', array_merge(userpoints_translation(), array('!node-name' => $name->name))),
          '#default_value' => variable_get(USERPOINTS_POST. $type, '0'),
          '#size'          => 5,
          '#maxlength'     => 5,
          );
      }

      $form[$group][USERPOINTS_POST_COMMENT] = array(
        '#type'          => 'textfield',
        '#title'         => t('!Points for posting a comment', userpoints_translation()),
        '#default_value' => variable_get(USERPOINTS_POST_COMMENT, 0),
        '#size'          => 5,
        '#maxlength'     => 5,
        );

      $form[$group][USERPOINTS_MODERATE_COMMENT] = array(
        '#type'          => 'textfield',
        '#title'         => t('!Points for moderating a comment', userpoints_translation()),
        '#default_value' => variable_get(USERPOINTS_MODERATE_COMMENT, 0),
        '#size'          => 5,
        '#maxlength'     => 5,
        );

      return $form;
      break;
  }
}
  
function userpoints_nodeapi(&$node, $op, $teaser, $page) {
  static $up_orig_uid;
  $points = variable_get(USERPOINTS_POST . $node->type, 0);
  switch($op) {
    case 'insert':
      $params = array(
        'points' => $points,
        'uid' => $node->uid,
        'operation' => 'insert',
        'entity_id' => $node->nid,
        'entity_type' => 'node'
      );
      userpoints_userpointsapi($params);
      break;
    case 'delete':
      $points = -$points;
      $params = array(
        'points' => $points,
        'uid' => $node->uid,
        'operation' => 'operation',
        'entity_id' => $node->nid,
        'entity_type' => 'node',
      );
      userpoints_userpointsapi($params);
      break;
    case 'prepare':
      $up_orig_uid = $node->uid;
      break;
    case 'update':
      //Find the last points granted on this node inserts and ownership gains
      $sql = "SELECT points, uid 
              FROM {userpoints_txn} 
              WHERE entity_id = %d AND entity_type = '%s' 
              AND (operation = '%s' OR operation ='%s')
              ORDER BY time_stamp DESC
              LIMIT 1
              ";
      $last_owner = db_fetch_object(db_query($sql, $node->nid, 'node','insert','Ownership gain'));
      
      //Check the UID of the original to this user, if different add/substract points
      if ($node->uid != $last_owner->uid && is_numeric($last_owner->uid) ) {
        //Check to see if this user has already lost the points for
        // Add to the new node owner
        $params = array(
          'points' => $points,
          'uid' => $node->uid,
          'operation' => 'Ownership gain',
          'entity_id' => $node->nid,
          'entity_type' => 'node'
        );
        userpoints_userpointsapi($params);
        // subtract from the original node owner
        $params = array(
          'points' => -$points,
          'uid' => $up_orig_uid,
          'operation' => 'Ownership loss',
          'entity_id' => $node->nid,
          'entity_type' => 'node'
        );
        userpoints_userpointsapi($params);
      }

      break;
  }
}

function userpoints_comment($comment, $op) {
  global $user;
  static $up_orig_uid;

  $points = variable_get(USERPOINTS_POST_COMMENT, 0);
  switch($op) {
    case 'insert':
      $params = array(
        'points' => $points,
        'uid' => $user->uid,
        'operation' => 'insert',
        'entity_id' => $comment['cid'],
        'entity_type' => 'comment'
      );
      userpoints_userpointsapi($params);
      break;
    case 'delete':
      $points = -$points;
      $params = array(
        'points' => $points,
        'uid' => $comment->uid,
        'operation' => 'delete',
        'entity_id' => $comment->cid,
        'entity_type' => 'comment'
      );
      userpoints_userpointsapi($params);
      break;
    case 'moderate':
      $points = variable_get(USERPOINTS_MODERATE_COMMENT, 0);
      $params = array(
        'points' => $points,
        'uid' => $comment->uid,
        'operation' => 'moderate',
        'entity_id' => $comment->cid,
        'entity_type' => 'comment'
      );
      userpoints_userpointsapi($params);
      break;
    case 'form':
      $up_orig_uid = $comment['uid']['#value'];
      break;
    case 'update':
      //Find the last points granted on this node inserts and ownership gains
      $sql = "SELECT points, uid 
              FROM {userpoints_txn} 
              WHERE entity_id = %d AND entity_type = '%s' 
              AND (operation = '%s' OR operation ='%s')
              ORDER BY time_stamp DESC
              LIMIT 1
              ";
      $cid = $comment['cid'];
      $new_uid = $comment['uid'];
      $last_owner = db_fetch_object(db_query($sql, $cid, 'comment','insert','Ownership gain'));

      //Check the UID of the original to this user, if different add/substract points
      if ($new_uid != $last_owner->uid && is_numeric($last_owner->uid) ) {
        //The owner has changed so we're removing from the
        //the original owner and giving to the new owner
        //Give to the original owner
        $points = $last_owner->points;
        $params = array(
          'points' => $points,
          'uid' => $new_uid,
          'operation' => 'Ownership gain',
          'entity_id' => $cid,
          'entity_type' => 'comment'
        );
        userpoints_userpointsapi($params);

        //Take away from the original owner
        $params = array(
          'points' => -$points,
          'uid' => $last_owner->uid,
          'operation' => 'Ownership loss',
          'entity_id' => $new_uid,
          'entity_type' => 'comment'
        );
        userpoints_userpointsapi($params);

      }
      break;
  }
}

