<?php
// $Id: userpoints.module,v 1.67.2.58 2010-05-16 21:43:36 kbahey Exp $

// Copyright 2005-2007 Khalid Baheyeldin http://2bits.com

define('USERPOINTS_PERM_VIEW',           'view userpoints');
define('USERPOINTS_PERM_VIEW_OWN',       'view own userpoints');
// The permission(PERM_USE) was removed from use as per #158490 it'll remain
// out until code exists to use the permission (jredding 12/26/2007)
define('USERPOINTS_PERM_USE',            'use userpoints');
define('USERPOINTS_PERM_ADMIN',          'administer userpoints');

define('USERPOINTS_TRANS_UCPOINTS',      'userpoints_trans_ucpoints');
define('USERPOINTS_TRANS_LCPOINTS',      'userpoints_trans_lcpoints');
define('USERPOINTS_TRANS_UCPOINT',       'userpoints_trans_ucpoint');
define('USERPOINTS_TRANS_LCPOINT',       'userpoints_trans_lcpoint');
define('USERPOINTS_TRANS_UNCAT',         'userpoints_trans_uncat');

define('USERPOINTS_STATUS',              'userpoints_status');

define('USERPOINTS_POINTS_MODERATION',    'userpoints_points_moderation');

define('USERPOINTS_TXN_STATUS_APPROVED',  0);
define('USERPOINTS_TXN_STATUS_PENDING',   1);
define('USERPOINTS_TXN_STATUS_DECLINED',  2);


define('USERPOINTS_EXPIRY_DESCRIPTION', 'userpoints_expiry_description');
define('USERPOINTS_EXPIREON_DATE', 'userpoints_expireon_date');
define('USERPOINTS_EXPIREAFTER_DATE', 'userpoints_expireafter_date');
define('USERPOINTS_DISPLAY_MESSAGE', 'userpoints_display_message');

define('USERPOINTS_REPORT_USERCOUNT', 'userpoints_report_usercount');
define('USERPOINTS_REPORT_LIMIT', 'userpoints_report_limit');
define('USERPOINTS_REPORT_DISPLAYZERO', 'userpoints_report_displayzero');

define('USERPOINTS_CATEGORY_NAME', 'Userpoints');
define('USERPOINTS_CATEGORY_DEFAULT_VID', 'userpoints_category_default_vid');
define('USERPOINTS_CATEGORY_DEFAULT_TID', 'userpoints_category_default_tid');
define('USERPOINTS_CATEGORY_PROFILE_DISPLAY_TID', 'userpoints_category_profile_display_tid');
define('USERPOINTS_TRANSACTION_TIMESTAMP', 'userpoints_transaction_timestamp');

/**
 * Returns an array of common translation placeholders.
 */
function userpoints_translation() {
  static $trans;

  if (!isset($trans)) {
    $trans = array(
      '!Points' => variable_get(USERPOINTS_TRANS_UCPOINTS, 'Points'),
      '!points' => variable_get(USERPOINTS_TRANS_LCPOINTS, 'points'),
      '!Point'  => variable_get(USERPOINTS_TRANS_UCPOINT, 'Point'),
      '!point'  => variable_get(USERPOINTS_TRANS_LCPOINT, 'point'),
      '!Uncategorized'  => variable_get(USERPOINTS_TRANS_UNCAT, 'Uncategorized'),
      );
  }
  return $trans;
}

/*
 * Returns an array of possible transaction statuses.
 */
function userpoints_txn_status() {
  return array(
      USERPOINTS_TXN_STATUS_APPROVED => t('Approved'),
      USERPOINTS_TXN_STATUS_PENDING  => t('Pending'),
      USERPOINTS_TXN_STATUS_DECLINED => t('Declined'),
      );
}

/**
 * Implements hook_help().
 */
function userpoints_help($path, $arg) {
  switch ($path) {
    case 'admin/settings/userpoints':
      return t('Configure userpoints moderation and branding translation');
    case 'admin/help#userpoints':
      return t('Users earn !points as they post nodes, comments, and vote on nodes', userpoints_translation());
  }
}

/**
 * Implements hook_menu().
 */
function userpoints_menu() {
  $items = array();
  $items['admin/config/people/userpoints'] = array(
    'title'            => '!Points',
    'title arguments'  => userpoints_translation(),
    'description'      => strtr('Manage !points', userpoints_translation()),
    'page callback'    => 'userpoints_admin_points',
    'access arguments' => array(USERPOINTS_PERM_ADMIN)
  );
  $items['admin/config/people/userpoints/list'] = array(
    'title'            => 'List',
    'title arguments'  => userpoints_translation(),
    'description'      => strtr('List users by !points', userpoints_translation()),
    'access arguments' => array(USERPOINTS_PERM_VIEW),
    'type'             => MENU_DEFAULT_LOCAL_TASK,
    'weight'           => -2,
  );
  $items['admin/config/people/userpoints/moderate'] = array(
    'title'            => 'Moderation',
    'title arguments'  => userpoints_translation(),
    'description'      => strtr('Review !points in moderation', userpoints_translation()),
    'page callback'    => 'userpoints_admin_manage',
    'access arguments' => array(USERPOINTS_PERM_ADMIN),
    'type'             => MENU_LOCAL_TASK,
    'weight'           => -1,
  );
  $items['admin/config/people/userpoints/add'] = array(
    'title'            => 'Add',
    'description'      => 'Admin add/delete userpoints',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('userpoints_admin_txn', 4, 5),
    'access arguments' => array(USERPOINTS_PERM_ADMIN),
    'type'             => MENU_LOCAL_TASK,
    'weight'           => 0,
  );
  $items['admin/config/people/userpoints/edit'] = array(
    'title'            => 'Edit',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('userpoints_admin_txn', 4, 5),
    'access arguments' => array(USERPOINTS_PERM_ADMIN),
    'type'             => MENU_CALLBACK
  );

  $items['admin/config/people/userpoints/approve'] = array(
    'title'            => 'Approve Userpoints',
    'page callback'    => 'userpoints_admin_approve',
    'page arguments'   => array(4, 5),
    'access arguments' => array(USERPOINTS_PERM_ADMIN),
    'type'             => MENU_CALLBACK
  );
  $items['admin/config/people/userpoints/decline'] = array(
    'title'            => t('Approve !points', userpoints_translation()),
    'page callback'    => 'userpoints_admin_approve',
    'page arguments'   => array(4, 5),
    'access arguments' => array(USERPOINTS_PERM_ADMIN),
    'type'             => MENU_CALLBACK
  );

  $items['admin/config/people/userpoints/settings'] = array(
    'title'            => '!Points settings',
    'description'      => strtr('Settings for !points', userpoints_translation()),
    'title arguments'  => userpoints_translation(),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('userpoints_admin_settings'),
    'access arguments' => array(USERPOINTS_PERM_ADMIN),
    'type'             => MENU_LOCAL_TASK,
    'weight'           => 10,
  );

  $items['userpoints'] = array(
    'title'            => 'Users by !points',
    'title arguments'  => userpoints_translation(),
    'page callback'    => 'userpoints_list_users',
    'access arguments' => array(USERPOINTS_PERM_VIEW),
    'type'             => MENU_NORMAL_ITEM,
  );

  $items['myuserpoints'] = array(
    'title'           => 'My !points',
    'title arguments' => userpoints_translation(),
    'page callback'   => 'userpoints_list_my_userpoints',
    'access callback' => 'userpoints_access_my_points',
    'type'            => MENU_NORMAL_ITEM
  );
  return $items;
}

/**
 * Checks if user can access their points - used via hook_menu().
 *
 * @return
 *   TRUE if user has permissions to view userpoints and if the user is logged
 *   in.
 */
function userpoints_access_my_points() {
  global $user;
  if ($user->uid === 1 || user_access(USERPOINTS_PERM_ADMIN)) {
    return TRUE;
  }
  return ( _userpoints_user_exists($user->uid) &&
					((user_access(USERPOINTS_PERM_VIEW) && user_is_logged_in()) || user_access(USERPOINTS_PERM_VIEW_OWN))
				 );
}

/**
 * Implements hook_perm().
 */
function userpoints_permission() {
  return array(
    USERPOINTS_PERM_VIEW => array(
      'name' => t('View all UserPoints'),
    ),
    USERPOINTS_PERM_VIEW_OWN => array(
      'name' => t('View own UserPoints'),
    ),
    USERPOINTS_PERM_ADMIN => array(
      'name' => t('Administer Userpoints')
    ));
}

/**
 * Implements hook_theme().
 */
function userpoints_theme() {
  return array(
    'userpoints_list_users' => array(
      'variables' => array(
        'header' => NULL,
        'rows' => NULL,
        'tid' => NULL,
        'pager_limit' => NULL,
        )
      ),
    'userpoints_list_users_header' => array(
	    'variables' => array()
	   ),
    'userpoints_list_users_row' => array(
      'variables' => array(
        'row' => NULL,
         )
    ),
    'userpoints_list_my_userpoints' => array(
      'variables' => array(
        'args' => NULL,
        'header' => NULL,
        'rows' => NULL,
        ),
    ),
  );
}

/**
 * Implements hook_tokens().
 */
function userpoints_tokens($type, $tokens, array $data = array(), array $options = array()) {
  if ($type == 'user' && isset($data['user']) && isset($tokens['userpoints'])) {
    return array($tokens['userpoints'] => userpoints_get_current_points($data['user']->uid));
  }
}

/**
 * Implements hook_token_list().
 */
function userpoints_token_list($type = 'all') {
  return array(
    'tokens' => array(
      'user'   => array(
        'name'   => t('User points'),
        'description' => t('The number of points a user has.'),
      )
    )
  );
}

/**
 * Menu callback for settings form.
 */
function userpoints_admin_settings($form, &$form_state) {
  $group = 'renaming';
  $form[$group] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('Points branding'),
  );

  $form[$group][USERPOINTS_TRANS_UCPOINTS] = array(
  '#type' => 'textfield',
  '#title' => t('Word to use in the interface for the upper case plural word !Points', userpoints_translation()),
  '#default_value' => variable_get(USERPOINTS_TRANS_UCPOINTS, 'Points'),
  '#size' => 20,
  '#maxlength' => 20,
  );

  $form[$group][USERPOINTS_TRANS_LCPOINTS] = array(
  '#type' => 'textfield',
  '#title' => t('Word to use in the interface for the lower case plural word !points', userpoints_translation()),
  '#default_value' => variable_get(USERPOINTS_TRANS_LCPOINTS, 'points'),
  '#size' => 20,
  '#maxlength' => 20,
  );
  $form[$group][USERPOINTS_TRANS_UCPOINT] = array(
  '#type' => 'textfield',
  '#title' => t('Word to use in the interface for the upper case singular word !Point', userpoints_translation()),
  '#default_value' => variable_get(USERPOINTS_TRANS_UCPOINT, 'Point'),
  '#size' => 20,
  '#maxlength' => 20,
  );
  $form[$group][USERPOINTS_TRANS_LCPOINT] = array(
  '#type' => 'textfield',
  '#title' => t('Word to use in the interface for the lower case singular word !point', userpoints_translation()),
  '#default_value' => variable_get(USERPOINTS_TRANS_LCPOINT, 'point'),
  '#size' => 20,
  '#maxlength' => 20,
  );
  $form[$group][USERPOINTS_TRANS_UNCAT] = array(
  '#type' => 'textfield',
  '#title' => t('Word to use for the uncategorized category'),
  '#default_value' => variable_get(USERPOINTS_TRANS_UNCAT, 'Uncategorized'),
  '#size' => 20,
  '#maxlength' => 20,
  );

  $group = 'status';
  $form[$group] = array(
    '#type' => 'fieldset',
    '#title' => t('Moderation'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#weight' => -1,
  );

  $form[$group][USERPOINTS_POINTS_MODERATION] = array(
    '#type'          => 'radios',
    '#title'         => t('Transaction status'),
    '#default_value' => variable_get(USERPOINTS_POINTS_MODERATION, 0),
    '#options'       => array(t('Approved'), t('Moderated')),
    '#description'   => t('Select whether all !points should be approved automatically, or moderated, and require admin approval', userpoints_translation()),
  );

  $group = "Points expiration";
  $form[$group] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('!Points expiration', userpoints_translation()),
    '#description' => t('These settings affect new !points only, they are not retroactive. !Points expiration depends upon cron.', userpoints_translation()),
  );

  $form[$group][USERPOINTS_EXPIREAFTER_DATE] = array(
    '#type' => 'select',
    '#title' => t('Expire !points after', userpoints_translation()),
    '#description' => t('Once !points have been obtained by the user
                          they will expire according to this setting',  userpoints_translation()),
    '#options' => expiry_dates(),
    '#default_value' => variable_get(USERPOINTS_EXPIREAFTER_DATE, NULL),
  );

  // If the expiration date is earlier than today/ new points will last forever.
  // Although this may be desirable/ it could also be an oversight so we'll
  // display a message to the administrator.
  $warning="";
  if (userpoints_date_to_timestamp(variable_get(USERPOINTS_EXPIREON_DATE, array('day' => 1, 'month' => 1, 'year' => 1900))) < time()) {
    $warning = '<br /><strong>'. t('This setting will not take affect, date must be in the future') .'</strong>';
  }

  $form[$group][USERPOINTS_EXPIREON_DATE] = array(
    '#type' => 'date',
    '#title' => t('Expire !points on this date', userpoints_translation()),
    '#description' => t('Once !points have been obtained by the user they will
                         last until this date. This setting overrides the
                         "Expire after setting" above ', userpoints_translation()). $warning,
    '#default_value' => variable_get(USERPOINTS_EXPIREON_DATE, array('day' => 1, 'month' => 1, 'year' => 1980)),
  );
  $form[$group][USERPOINTS_EXPIRY_DESCRIPTION] = array(
    '#type' => 'textarea',
    '#title' => t('Expiration entry description'),
    '#description' => t('A negating expiration entry is made to expire
                         !points leaving the original entry intact
                         (e.g. original !points + expiration !points = 0).
                         When the expiration entry is made this description will
                         be placed on the entry. This is useful so the users will
                         know what happened to their !point balance. In crafting
                         your message you can use the following variables.',
 												 userpoints_translation()). t('
                         <br /> !points = The name used in branding
                         above (also use !Points and !point)'). t('
                         <br /> !operation = Original operation that granted the !points
                         <br /> !description = Original description for the !point
                         <br /> !txn_id Original transaction ID
                         <br /> !date = Date of the original entry',  userpoints_translation()),
    '#default_value' => variable_get(USERPOINTS_EXPIRY_DESCRIPTION, ''),
  );

  $group = "misc";
  $form[$group] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('Messages'),
    '#description' => t('Control the behavior of messages users see. '),
  );

  $form[$group][USERPOINTS_DISPLAY_MESSAGE] = array(
    '#type'          => 'radios',
    '#title'         => t('Display message'),
    '#default_value' => variable_get(USERPOINTS_DISPLAY_MESSAGE, 1),
    '#options'       => array(0 => t('No'), 1 => t('Yes')),
    '#description'   => t('Determines if a message should be displayed whenever !points are awarded/substracted ', userpoints_translation()),
  );
  $group = "reports";
  $form[$group] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('Report Settings'),
    '#description' => t(''),
  );

  $form[$group][USERPOINTS_REPORT_LIMIT] = array(
    '#type'          => 'select',
    '#title'         => t('Transactions per page'),
    '#default_value' => variable_get(USERPOINTS_REPORT_LIMIT, 10),
    '#options'       => array(10 => 10, 20 => 20, 30 => 30, 40 => 40, 50 => 50, 100 => 100),
    '#description'   => t('Limits the number of transactions displayed per page'),
  );
  $form[$group][USERPOINTS_REPORT_DISPLAYZERO] = array(
    '#type'          => 'radios',
    '#title'         => t('Display zero !point users?', userpoints_translation()),
    '#default_value' => variable_get(USERPOINTS_REPORT_DISPLAYZERO, 1),
    '#options'       => array(t('No'), t('Yes')),
    '#description'   => t('If set to "No" users with zero !points will not be displayed in the reports ', userpoints_translation()),
  );
  $form[$group][USERPOINTS_REPORT_USERCOUNT] = array(
    '#type'          => 'select',
    '#title'         => t('Users per page'),
    '#default_value' => variable_get(USERPOINTS_REPORT_USERCOUNT, 30),
    '#options'       => array(10 => 10, 20 => 20, 30 => 30, 40 => 40, 50 => 50, 100 => 100),
    '#description'   => t('When listing !points by user limit how many users are displayed on a single page', userpoints_translation()),
  );


  // Categories will only appear if the taxonomy module is enabled as
  // the module is required for this functionality but not necessarily
  // a requirement for the module.
  if (module_exists('taxonomy')) {
    $group = 'category';
    $form[$group] = array(
      '#type' => 'fieldset',
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#title' => t('!Points Categorization', userpoints_translation()),
    );
    $form[$group][USERPOINTS_CATEGORY_DEFAULT_TID] = array(
      '#type' => 'select',
      '#title' => t('Default Category'),
      '#default_value' => variable_get(USERPOINTS_CATEGORY_DEFAULT_TID, NULL),
      '#options' =>  userpoints_get_categories(),
      '#description' => t('By default all !points are assigned to this category.  You can modify what categories are available by modifying the <a href="!url">Userpoints taxonomy</a>',
        array_merge(userpoints_translation(), array('!url' => url('admin/content/taxonomy/'. variable_get(USERPOINTS_CATEGORY_DEFAULT_VID, ''))))),
    );
    $options = userpoints_get_categories();
    // $options doesn't include all so we'll add it.
    $options['all'] = t('All categories');
	  $form[$group][USERPOINTS_CATEGORY_PROFILE_DISPLAY_TID] = array(
	    '#type' => 'select',
	    '#title' => t('Category to display on the user profile page'),
	    '#default_value' => variable_get(USERPOINTS_CATEGORY_PROFILE_DISPLAY_TID, NULL),
	    '#options' =>  $options,
	    '#description' => t('Select which category of !points to display on the user profile page. Select "All" to display a sum total of all categories', userpoints_translation()),
	  );
  }
  // New configuration options to overide current timestamp.
  $group = "stamping";
  $form[$group] = array(
    '#type'        => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed'   => TRUE,
    '#title'       => t('Transaction stamping'),
    '#description' => t(''),
  );
  $form[$group][USERPOINTS_TRANSACTION_TIMESTAMP] = array(
    '#type'          => 'checkbox',
    '#title'         => t('Always use system time'),
    '#default_value' => variable_get(USERPOINTS_TRANSACTION_TIMESTAMP, 1),
    '#description'   => t('Sets if the transaction timestamp should obey current time, or can be modified by the API operations. Unchecking this option will allow customization of timetamp for the transactions.'),
  );

  $form['setting'] = module_invoke_all('userpoints', 'setting');
  return system_settings_form($form);
}

/**
 * Get current points of a user.
 *
 * @param $uid
 *   User id of the user to get or lose the points.
 *
 * @return
 *   Number of current points in that user's account.
 */
function userpoints_get_current_points($uid = NULL, $tid = NULL) {
  if (!$uid) {
    global $user;
    $uid = $user->uid;
  }
  if (!$tid) {
    $tid = userpoints_get_default_tid();
  }
  elseif ($tid == 'all') {
    return (int)db_query('SELECT SUM(points) FROM {userpoints} WHERE uid = :uid', array(':uid' => $uid))->fetchField();
  }
  return (int)db_query('SELECT points FROM {userpoints} WHERE uid = :uid AND tid = :tid', array(':uid' => $uid, ':tid' => $tid))->fetchField();
}

/**
 * Gets the number of maximal points of that user.
 *
 * @param $uid
 *   User id of the user to get or lose the points.
 *
 * @return
 *   Number of max points in that user's account.
 */
function userpoints_get_max_points($uid = NULL, $tid = NULL) {
  $max = drupal_static(__FUNCTION__, array());

  // Check if uid is passed as a parameter.
  if (!$uid) {
    // It is not, so we use the currently logged in user's uid.
    global $user;
    $uid = $user->uid;
  }

  // Check if a term id is passed as a parameter.
  if (!$tid) {
    // It is not, so get the default term id.
    $tid = userpoints_get_default_tid();
  }

  // Check if we have already cached the maximum for the user/term combination on previous calls.
  if (!isset($max[$uid][$tid])) {
    // We did not cache it.
    if ($tid == 'all') {
      // There is no term id, so we use "all".
      $max[$uid][$tid] = db_query('SELECT SUM(max_points) FROM {userpoints} WHERE uid = :uid', array(':uid' => $uid))->fetchField();
    }
    else {
      // A term ID is specified, so fetch its maximum points.
      $max[$uid][$tid] = db_query('SELECT max_points FROM {userpoints} WHERE uid = :uid AND tid = :tid', array(':uid' => $uid, ':tid' => $tid))->fetchField();
    }
  }
  // Return the cached value.
  return $max[$uid][$tid];
}

/**
 * Save userpoint changes and call hooks.
 *
 * @param $params
 *    if (int) assumed to be points for current user
 *    Accepts an array of keyed variables and parameters
 *    'points' => # of points (int) (required)
 *    'moderate' => TRUE/FALSE
 *    'uid' => $user->uid
 *    'time_stamp' => unix time of the points assignement date
 *    'operation' => 'published' 'moderated' etc.
 *    'tid' => 'category ID'
 *    'expirydate' => timestamp or 0, 0 = non-expiring; NULL = site default
 *    'description' => 'description'
 *    'reference' => reserved for module specific use
 *    'display' => whether or not to display "points awarded" message
 *    'txn_id' => Transaction ID of points, If present an UPDATE is performed
 *    'entity_id' => ID of an entity in the Database. ex. $node->id or $user->uid
 *    'entity_type' => string of the entity type. ex. 'node' or 'user' NOT 'node-content-custom'
 *
 * @return
 *   Array with status and reason.
 *     'status' => FALSE when no action is take, TRUE when points are credited or debited
 *     'reason' => (string) error message to indicate reason for failure
 */
function userpoints_userpointsapi($params) {
  // Test for the existence of parameters and set defaults if necessary.
  if (!isset($params['txn_id'])) {
    // If a txn_id is passed in we'll do an UPDATE thus the std checks don't apply.
    if (is_int($params)) {
      $params = array('points' => $params);
    }
    if (!is_array($params)) {
      // Has to be an array to continue.
      return array(
        'status' => false,
        'reason' => 'Parameters did not properly form as an array,
                     this is an internal module error.
                    ',
      );
    }
    if (!isset($params['uid'])) {
      global $user;
      $params['uid'] = $user->uid;
    }

    // Check if parameters are set.
    $params_null_check = array('operation', 'description', 'reference', 'display', 'entity_id', 'entity_type');
    foreach($params_null_check as $param_null_check) {
      if (!isset($params[$param_null_check])) {
        $params[$param_null_check] = NULL;
      }
    }

    if (!isset($params['moderate'])) {
      // If not passed then site default is used.
      $params['status'] = variable_get(USERPOINTS_POINTS_MODERATION, 0);
    }
    else {
      if ($params['moderate'] == true) {
        $params['status'] = 1;
      }
      else {
        $params['status'] = 0;
      }
    }
    if (!isset($params['tid']) || !is_numeric($params['tid'])) {
      // If not passed then site default is used.
      $params['tid'] = userpoints_get_default_tid();
    }

    // Anonymous users do not get points, and there have to be points to process.
    if (($params['uid'] == 0 || $params['points'] == 0)) {
      return array(
        'status' => false,
        'reason' => 'uid or points = 0. Anonymous users do not get points
                     and there must be points to process.',
      );
    }
  }
  else {
    // We have a txn_id so we can look up some user information.
    $params['uid'] = db_query('SELECT uid from {userpoints_txn} WHERE txn_id = :txn_id', array(':txn_id' => $params['txn_id']))->fetchField();
  } // If txn_id.

  // Load the user object that will be awarded the points.
  $name = db_query('SELECT name FROM {users} WHERE uid = :uid', array(':uid' => $params['uid']))->fetchField();
  if (!$name) {
    return array(
      'status' => false,
      'reason' => 'invalid uid or user account could not be loaded',
    );
  }

  // Call the _userpoints hook, and stop if one of them returns FALSE.
  $rc = module_invoke_all('userpoints', 'points before', $params);

  foreach ($rc as $key => $value) {
    if ($value == FALSE) {
      // Do not process the points.
      return array(
        'status' => false,
        'reason' => t('@key returned false from the hook_userpoints points before call', array('@key' => $key)),
      );
    }
  }
  if ($params['points'] < 0) {
    $msg = t('lost');
  }
  elseif ($params['status'] == 2) {
    // Points have been declined.
    $msg = t('was declined');
  }
  else {
    $msg = t('earned');
  }

  $ret = _userpoints_transaction($params);
  if ($ret == false) {
    return array(
      'status' => false,
      'reason' => 'transaction failed in _userpoints_transaction, this is an internal module error',
    );
  }

  if ($params['status'] == 1) {
    $mesg = (t('User %uname %op %pointsvalue !points, pending administrator approval.',
      array_merge(userpoints_translation(), array(
        '%uname'  => $name,
        '%op'     => $msg,
        '%pointsvalue' => abs($params['points']),
        '%total'  => userpoints_get_current_points($params['uid'], $params['tid']),
        ))
      ));
  }
  else {
    $mesg = (t('User %uname %op %pointsvalue !points Total now is %total !points.',
      array_merge(userpoints_translation(), array(
        '%uname'  => $name,
        '%op'     => $msg,
        '%pointsvalue' => abs($params['points']),
        '%total'  => userpoints_get_current_points($params['uid'], $params['tid'])
        ))));
  }

  if ($mesg && (isset($params['display']) || ($params['display'] === null && variable_get(USERPOINTS_DISPLAY_MESSAGE, 1) == 1))) {
    drupal_set_message($mesg);
  }
  // Call the _userpoints hook to allow modules to act after points are awarded.
  module_invoke_all('userpoints', 'points after', $params);
  return array(
    'status' => true,
  );
}

/**
 * Adds the points to the txn table.
 */
function _userpoints_transaction(&$params) {
  // Check, again, for a properly formed array.
  if (!is_array($params)) {
    return false;
  }
  if (!isset($params['txn_id'])) {
    // If a txn_id is preset we UPDATE the record instead of adding one
    // the standard checks don't apply.
    if (!is_numeric($params['points'])) {
      return false;
    }
    if (!isset($params['uid'])) {
      global $user;
      $params['uid'] = $user->uid;
      // There must be a UID, anonymous does not receive points.
      if (!$params['uid'] > 0) {
        return false;
      }
    }
    if (!isset($params['moderate'])) {
      // If not passed then site default is used.
      $params['status'] = variable_get(USERPOINTS_POINTS_MODERATION, 0);
    }
    else {
      if ($params['moderate'] == true) {
        $params['status'] = 1;
      }
      else {
        $params['status'] = 0;
      }
    }
    if (isset($params['expirydate']) && !is_numeric($params['expirydate'])) {
      return false;
    }

    // Check if parameters are set.
    $params_null_check = array('operation', 'description', 'reference', 'expired', 'parent_txn_id', 'entity_id', 'entity_type');
    foreach($params_null_check as $param_null_check) {
      if (!isset($params[$param_null_check])) {
        $params[$param_null_check] = NULL;
      }
    }

    if (!isset($params['tid']) || !is_numeric($params['tid'])) {
      $params['tid'] = userpoints_get_default_tid();
    }
    elseif ($params['tid'] == 0) {
      // Tid with 0 are uncategorized and are set to NULL
      // this is a backwards compatibilty issue.
      $params['tid'] = NULL;
    }
    if (!isset($params['expirydate'])) {
      $params['expirydate'] = userpoints_get_default_expiry_date();
    }
  } // If txn_id.

  // Control time_stamp functionality, by default with current timestamp.
  $time = time();
  // Overide system time if meeting criteria matches: Don't let future timestamps, Don't let bad formated timestamps.
  if (variable_get(USERPOINTS_TRANSACTION_TIMESTAMP, 1) || !isset($params['time_stamp']) || !is_numeric($params['time_stamp']) || $params['time_stamp'] > $time || $params['time_stamp'] < 0) {
      $params['time_stamp'] = $time;
  }
  // Always force changed timestamp to current time() for transaction tracking.
  $params['changed'] = $time;

  if (!empty($params['txn_id']) && is_numeric($params['txn_id'])) {
    // A transaction ID was passed in so we'll update the transaction.
    $txn = db_query("SELECT txn_id, uid, approver_uid, points,
      time_stamp, status, operation, description, reference, expirydate, expired,
      parent_txn_id, tid, entity_id, entity_type
      FROM {userpoints_txn}
      WHERE txn_id = :txn_id",
      array(':txn_id' => $params['txn_id']))->fetchAssoc();

    // Don't superseed existing keys, just complete missing keys.
    $params += $txn;
    // Update existing transaction record for key txn_id.
    $ret = drupal_write_record('userpoints_txn', $params, array('txn_id'));
    // Only update if the record has been successfully updated.
    if ($ret != FALSE) {
    _userpoints_update_cache($params);
  }
  }
  else {
    // Create new transaction record.
    $ret = drupal_write_record('userpoints_txn', $params);
    // Don't cache entry if it's pending.
    if ($params['status'] != TRUE && $ret != FALSE) {
      _userpoints_update_cache($params);
    }
  }
  return TRUE;
}

/**
 * Update the caching table
 */
function _userpoints_update_cache(&$params) {
  if ( $params['status'] != 0 || $params['expired'] == 1) {
      // Only update the cache for fully approved non-expired points.
      return false;
  }
  if (!isset($params['tid'])) {
    $params['tid'] = 0;
  }

  // Calculate the current points based upon the tid.
  $current_points = (int)$params['points'] + userpoints_get_current_points($params['uid'], $params['tid']);
  // Grab the user's maximum points to preserve it.
  $max_points = (int)db_query('SELECT max_points FROM {userpoints} WHERE uid = :uid AND tid = :tid',
    array(':uid' => $params['uid'], ':tid' => (int)$params['tid']))->fetchField();
  if ($params['points'] > 0) {
    // Points are greater than zero, update their max_points.
    $max_points = (int)$params['points'] + (int)$max_points;
  }

  // Insert or update the userpoints caching table with the user's current points.
  //debug($params);
  //debug($current_points);
  //debug($max_points);
  db_merge('userpoints')
    ->key(array(
      'uid' => $params['uid'],
      'tid' => (int)$params['tid'],
    ))
    ->fields(array(
      'points' => (int)$current_points,
      'max_points' => (int)$max_points,
      'last_update' => REQUEST_TIME,
    ))
    ->execute();
  unset($params);
}


/**
 * Determines the correct default expiration date.
 *
 * @return
 *   The default expiration date.
 */
function userpoints_get_default_expiry_date() {
  $expirydate = userpoints_date_to_timestamp(variable_get(USERPOINTS_EXPIREON_DATE, NULL));
  if ($expirydate < time()) {
    $expirydate = variable_get(USERPOINTS_EXPIREAFTER_DATE, NULL);
    if ($expirydate) {
      $expirydate = time() + $expirydate;
    }
  }
  return $expirydate;
}

/*
 * Checks to ensure that a user exists corresponding to a category.
 *
 * @param $uid
 *   User ID to check for existence of points for the user.
 * @param $tid
 *   taxonomy id of the category to limit to, if omitted
 *   if the use has points in any category the return is true.
 * @return
 *  TRUE if user found, FALSE otherwise.
 */
function _userpoints_user_exists($uid, $tid = NULL) {
  if (is_numeric($tid) ) {
    return (int)db_query('SELECT COUNT(uid)
      FROM {userpoints}
      WHERE uid = :uid AND tid = :tid',
      array(':uid' => $uid, ':tid' => $tid))->fetchField();
  }
  else {
    return (int)db_query('SELECT COUNT(uid)
      FROM {userpoints}
      WHERE uid = :uid',
      array(':uid' => $uid))->fetchField();

  }
}

/**
 * Implements hook_user_delete().
 */
function userpoints_user_delete($account) {
  // The user is being deleted, delete all traces in userpoints and txn tables.
  db_delete('userpoints')
    ->condition('uid', $account->uid)
    ->execute();
  db_delete('userpoints_txn')
    ->condition('uid', $account->uid)
    ->execute();
}

/**
 * Implements hook_user_view().
 */
function userpoints_user_view($account, $view_mode) {
  global $user;
  if (user_access(USERPOINTS_PERM_VIEW) || (user_access(USERPOINTS_PERM_VIEW_OWN) && $user->uid == $account->uid )) {
    $details = null;
    if (userpoints_access_my_points()) {
      $details .= l(t('View'), 'myuserpoints/' . $account->uid, array('attributes' => array('title' => t('View detailed transactions'))));
    }
    if (user_access(USERPOINTS_PERM_ADMIN)) {
      if (!is_null($details)) {
        $details .= ', ';
      }
      $details .= l(t('Adjust'), 'admin/config/people/userpoints/add/' . $account->uid, array('attributes' => array('title' => t('Add/substract !points from this user', userpoints_translation()))));
    }

    // Which points are we displaying.
    $points = userpoints_get_current_points($account->uid, variable_get(USERPOINTS_CATEGORY_PROFILE_DISPLAY_TID, 0));

    $account->content['userpoints'] = array(
      '#type' => 'user_profile_category',
      '#title' => t('User !points', userpoints_translation()),
    );
    $account->content['userpoints']['points'] = array(
      '#type' => 'user_profile_item',
      '#title' => t('!Points', userpoints_translation()),
      '#value' => $details ? $points .' - '. $details : $points,
    );
  }
}

function userpoints_admin_manage($tid = NULL) {
  $cat_count = count(userpoints_get_categories());

  $header = array(
    array('data' => t('User'), 'field' => 'uid'),
    array('data' => t('Time stamp'), 'field' => 'time_stamp', 'sort' => 'desc'),
    array('data' => t('!Points', userpoints_translation()), 'field' => 'points'),
    array('data' => t('Operation'), 'field' => 'operation'),
    array('data' => t('Category'), 'field' => 'cat'),
    array('data' => t('Operation')),
  );

  $query = db_select('userpoints_txn', 'p')->extend('PagerDefault')->extend('TableSort')
    ->fields('p', array('txn_id', 'uid', 'time_stamp', 'points', 'operation', 'status', 'entity_type', 'entity_id'))
    ->condition('p.status', USERPOINTS_TXN_STATUS_PENDING)
    ->orderByHeader($header)
    ->limit(variable_get(USERPOINTS_REPORT_USERCOUNT, 30));

  $query->leftJoin('taxonomy_term_data', 't', 'p.tid = t.tid');
  $query->addField('t', 'name', 'cat');

  // Check for filtering.
  if (is_numeric($tid) && $tid == 0) {
    $query->condition(db_or()->isNull('p.tid')->condition('p.tid', ''));
    $cat = t('!Uncategorized', userpoints_translation());
  }
  elseif (is_numeric($tid)) {
    $query->condition('p.tid', $tid);
    $cat = db_query("SELECT name from {taxonomy_term_data} WHERE tid = :tid", array(':tid' => $tid));
  }
  else {
    $cat = t('All');
  }

  // Set the title of the page.
  // @todo: translation of $cat => t() is wrong.
  drupal_set_title($cat . ' ' . t('!points', userpoints_translation()));
  $rows = array();
  foreach ($query->execute() as $data) {
    $user = user_load(array('uid' => $data->uid));
    if (!$data->cat) {
      $data->cat = t('!Uncategorized', userpoints_translation());
    }
    $operations = module_invoke_all('userpoints', 'entity_type', $data);
    if (is_array($operations) && isset($operations[0])) {
      $operation = $operations[0];
    }
    else {
      switch ($data->entity_type) {
        case 'node' :
          $node = node_load($data->entity_id);
          if ($node) {
            $operation = l($data->operation, 'node/'. $node->nid, array('attributes' => array('title' => $node->title)));
          }
          else {
            $operation = $data->operation;
          }
          break;
        case 'comment' :
          if (module_exists('comment')) {
            //We have to load the comment to get the nid for the comment
            $comment = _comment_load($data->entity_id);
            if ($comment) {
              $operation = l($data->operation, 'node/' . $comment->nid, array('attributes' => array('title' => $comment->subject), 'fragment' => 'comment-' . $comment->cid));
            }
            else {
              $operation = $data->operation;
            }
          }
          break;
        default:
          $operation = $data->operation;
      }
    }
    $rows[] = array(
      array('data' => theme('username', array('acount' => $user))),
      array('data' => format_date($data->time_stamp, 'custom', 'Y-m-d H:i')),
      array('data' => $data->points, 'align' => 'right'),
      array('data' => $operation),
      array('data' => $data->cat),
      array('data' => l('approve', "admin/config/people/userpoints/approve/$data->txn_id") .
        ' '. l('decline', "admin/config/people/userpoints/decline/$data->txn_id") .
        ' '. l('edit',    "admin/config/people/userpoints/edit/$data->txn_id")
      ),
    );
  }

  $output = '';
  if ($cat_count > 1) {
    $output = drupal_get_form('userpoints_filter_cat_select', 'admin/config/people/userpoints/moderate/', $tid);
  }
  $output .= theme('table', array('header' => $header, 'rows' =>  $rows, 'empty' => t('No !points awaiting moderation', userpoints_translation())));
  $output .= theme('pager');
  return $output;
}

/**
 * Approves moderated points.
 */
function userpoints_admin_approve($operation, $txn_id) {
  return drupal_get_form('userpoints_confirm_approve', $operation, (int)$txn_id);
}

function userpoints_confirm_approve($form_state, $operation, $txn_id) {
  $form = array(
    'operation' => array(
      '#type' => 'value',
      '#value' => $operation,
    ),
    'txn_id' => array(
      '#type' => 'value',
      '#value' => $txn_id,
    ),
  );

  return confirm_form(
    $form,
    t('Are you sure you want to @op txn @txn_id', array('@op' => $operation, '@txn_id' => $txn_id)),
    'admin/config/people/userpoints/moderate'
    );
}

function userpoints_confirm_approve_submit($form, &$form_state) {
  global $user;

  switch ($form_state['values']['operation']) {
    case 'approve':
      $status = USERPOINTS_TXN_STATUS_APPROVED;
      break;
    case 'decline':
      $status = USERPOINTS_TXN_STATUS_DECLINED;
      break;
    default:
      return false;
  }

  $params = array(
    'txn_id'       => $form_state['values']['txn_id'],
    'approver_uid' => $user->uid,
    'status'       => $status,
  );

  userpoints_userpointsapi($params);

  $form_state['redirect'] = 'admin/config/people/userpoints/moderate';
}

function userpoints_admin_txn($form, &$form_state, $mode, $txn_id) {
  global $user;

  $timestamp = format_date(time(), 'custom', 'Y-m-d H:i O');

  if ($mode == 'edit' && $txn_id) {
    $txn = db_query('SELECT * FROM {userpoints_txn} WHERE txn_id = :txn_id', array(':txn_id' => $txn_id))->fetch();
    $timestamp = format_date($txn->time_stamp, 'custom', 'Y-m-d H:i O');
    $txn_user = user_load($txn->uid);
  }
  elseif ($mode == 'add' && $txn_id) {
    $txn_user = user_load($txn_id);
  }

  $form['txn_user'] = array(
    '#type'          => 'textfield',
    '#title'         => t('User Name'),
    '#size'          => 30,
    '#maxlength'     => 60,
    '#default_value' => isset($txn_user) ? $txn_user->name : '',
    '#autocomplete_path' => 'user/autocomplete',
    '#description'   => t('User Name for the user you want the !points to affect', userpoints_translation()),
    );

  $form['points'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Points'),
    '#size'          => 10,
    '#maxlength'     => 10,
    '#default_value' => isset($txn->points) ? $txn->points : 0,
    '#description'   => t('Number of !points to add/subtract from the user. For example, 25 (to add !points) or -25 (to subtract !points).', userpoints_translation()),
    );

  $form['time_stamp'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Date/Time'),
    '#default_value' => $timestamp,
    '#size'          => 30,
    '#maxlength'     => 30,
    '#description'   => t('Date and time of this transaction, in the form YYYY-MM-DD HH:MM +ZZZZ'),
    );

  if (isset($txn->txn_id)) {
    if ($txn->expirydate > 0) {
      $expirydate = format_date($txn->expirydate, 'custom', 'Y-m-d H:i O');
    }
  }
  else {
    // If we're not editing we use site defaults.
    $expirydate = userpoints_get_default_expiry_date();
    if ($expirydate) {
      $expirydate = format_date($expirydate, 'custom', 'Y-m-d H:i O');
    }
  }
  $form['expirydate'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Expiration date'),
    '#default_value' => $expirydate,
    '#size'          => 30,
    '#maxlength'     => 30,
    '#description'   => t('Date and time to expire these !points, in the form YYYY-MM-DD HH:MM +ZZZZ', userpoints_translation()) .
                        '<br />'. t('Leave blank for non-expiring !points',  userpoints_translation()),
  );
  if (module_exists('taxonomy')) {
    $form['tid'] = array(
      '#type' => 'select',
      '#title' => t('Category'),
      '#default_value' => variable_get(USERPOINTS_CATEGORY_DEFAULT_TID, 0),
      '#options' =>  userpoints_get_categories(),
      '#description' => t('Category to apply these !points to', userpoints_translation()),
    );
  }

  $form['reference'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Reference'),
    '#default_value' => isset($txn->reference) ? $txn->reference : '',
    '#size'          => 30,
    '#maxlength'     => 128,
    '#description'   => t('Enter optional reference for this transaction. This field will be indexed and searchable.'),
    );

  $form['description'] = array(
    '#type'          => 'textarea',
    '#title'         => t('Description'),
    '#default_value' => isset($txn->description) ? $txn->description : '',
    '#width'         => 70,
    '#lines'         => 5,
    '#description'   => t('Enter an optional description for this transaction, such as the reason it is created.'),
    );


  switch ($mode) {
    case 'add':
      $form['approver_uid'] = array(
        '#type'  => 'hidden',
        '#value' => $user->uid,
        );

      $form['operation'] = array(
        '#type'  => 'hidden',
        '#value' => 'admin',
        );

      $form['status'] = array(
        '#type'  => 'hidden',
        '#value' => USERPOINTS_TXN_STATUS_PENDING,
        );

      $form['mode'] = array(
        '#type'  => 'hidden',
        '#value' => $mode,
        );
      break;

    case 'edit':

      $form['txn_user']['#disabled'] = true;
      unset($form['txn_user']['#autocomplete_path']);

      $form['txn_uid'] = array(
        '#type'  => 'value',
        '#value' => $txn->uid,
        );
      $form['txn_id'] = array(
        '#type'  => 'value',
        '#value' => $txn_id,
        );
      $form['approver_uid'] = array(
        '#type'  => 'textfield',
        '#description' => t('Approver ID'),
        '#default_value' => $txn->approver_uid,
        '#size'          => 10,
        '#maxlength'     => 7,
        '#description'   => t('The user ID of the person who approved this transaction. 0 means not yet approved.'),
        );

      $form['operation'] = array(
        '#type'  => 'textfield',
        '#description' => t('Operation'),
        '#default_value' => $txn->operation,
        '#size'          => 20,
        '#maxlength'     => 20,
        '#description'   => t('The operation type for this transaction. Normally, it is "admin".'),
        );

      $form['status'] = array(
        '#title' => t('Approval status'),
        '#type' => 'radios',
        '#options' => userpoints_txn_status(),
        '#description' => t('Approval status of the transaction.'),
        '#default_value' => $txn->status,
        );
      break;
  }

  $form['mode'] = array(
      '#type'  => 'hidden',
      '#default_value' => $mode
      );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
    );

  return $form;
}

function userpoints_admin_txn_submit($form, &$form_state) {
  if ($form_state['values']['form_id'] != 'userpoints_admin_txn') {
    return;
  }

  $txn_user = user_load_by_name($form_state['values']['txn_user']);
  switch ($form_state['values']['mode']) {
    case 'add':
      $params = array(
                  'points' => $form_state['values']['points'],
                  'uid' => $txn_user->uid,
                  'operation' => 'admin',
                  'description' => $form_state['values']['description'],
                  'reference' => $form_state['values']['reference'],
                  'tid' => $form_state['values']['tid'],
                  'time_stamp' => strtotime($form_state['values']['time_stamp']),
                );
      if ($form_state['values']['expirydate']) {
        // Check for the existence of an expirydate.
        $params['expirydate'] = strtotime($form_state['values']['expirydate']);
      }
      userpoints_userpointsapi($params);
      break;

    case 'edit':
      if ($form_state['values']['expirydate']) {
        $expirydate = strtotime($form_state['values']['expirydate']);
      }
      $params = array(
        'uid' => $form_state['values']['txn_uid'],
        'approver_id' => $form_state['values']['approver_uid'],
        'points' => $form_state['values']['points'],
        'time_stamp' => strtotime($form_state['values']['time_stamp']),
        'operation' => $form_state['values']['operation'],
        'description' => $form_state['values']['description'],
        'reference' => $form_state['values']['reference'],
        'status' => $form_state['values']['status'],
        'expirydate' => $expirydate,
        'txn_id' => $form_state['values']['txn_id']
      );
      userpoints_userpointsapi($params);
  }

  $form_state['redirect'] = 'admin/config/people/userpoints';
}

/**
 * Provides an administrative interface for managing points.
 */
function userpoints_admin_points($tid = NULL) {
  $cat_count = count(userpoints_get_categories());

  $header = array(
    array('data' => t('User'), 'field' => 'u.name'),
    array('data' => t('Category'), 'field' => 't.name'),
    array('data' => t('!Points', userpoints_translation()), 'field' => 'p.points', 'sort' => 'desc'),
  );

  $query = db_select('userpoints', 'p')->extend('PagerDefault')->extend('TableSort')
    ->fields('p', array('uid', 'points', 'tid'))
    ->fields('u', array('name'))
    ->groupBy('p.uid')
    ->groupBy('u.name')
    ->groupBy('p.points')
    ->groupBy('p.tid')
    ->groupBy('t.name')
    ->orderByHeader($header)
    ->limit(variable_get(USERPOINTS_REPORT_USERCOUNT, 30));

  $query->join('users', 'u', 'p.uid = u.uid');
  $query->leftJoin('taxonomy_term_data', 't', 'p.tid = t.tid');
  $query->addField('t', 'name', 'cat');

  // Check for filtering.
  if ($tid === 0) {
    $query->condition('p.tid', 0);
    $cat = t('!Uncategorized', userpoints_translation());
  }
  elseif (is_numeric($tid)) {
    $query->condition('p.tid', $tid);
    $cat = db_query("SELECT name from {taxonomy_term_data} WHERE tid = :tid", array(':tid' => $tid))->fetchField();
  }
  else {
    $cat = t('All');
  }
  drupal_set_title($cat ." ". t("!points", userpoints_translation()));

  if (variable_get(USERPOINTS_REPORT_DISPLAYZERO, 1) == 0 ) {
    // The user would NOT like to see users with zero points.
    $query->condition('p.points', 0, '<>');
  }

  $rows = array();
  foreach ($query->execute() as $data) {
    if (!$data->cat) {
      $data->cat = t('!Uncategorized', userpoints_translation());
    }
    $rows[] = array(
      array('data' => theme('username', array('account' => $data)) . "&nbsp;&nbsp;" . l(t("(details)"), "myuserpoints/$data->uid")),
      array('data' => $data->cat, 'align' => 'right'),
      array('data' => $data->points, 'align' => 'right'),
    );
  }

  // If there is only one category there is no sense in display the category filter dropdown.
  $output = '';
  if ($cat_count > 1) {
    $output = drupal_get_form('userpoints_filter_cat_select', 'admin/config/people/userpoints/', $tid);
  }
  $output .= theme('table', array('header' => $header, 'rows' => $rows));
  $output .= theme('pager');

  return $output;
}

/**
 * Lists the users and their point totals by all or by category.
 */
function userpoints_list_users($tid = NULL) {

  $header = theme('userpoints_list_users_header');
  $query = db_select('userpoints', 'p')->extend('PagerDefault')->extend('TableSort')
    ->fields('p', array('uid', 'points', 'tid'))
    ->fields('u', array('name'))
    ->groupBy('p.uid')
    ->groupBy('u.name')
    ->groupBy('p.points')
    ->groupBy('p.tid')
    ->groupBy('t.name')
    ->orderByHeader($header)
    ->limit(variable_get(USERPOINTS_REPORT_USERCOUNT, 30));

  $query->join('users', 'u', 'p.uid = u.uid');
  $query->leftJoin('taxonomy_term_data', 't', 'p.tid = t.tid');
  $query->addField('t', 'name', 'cat');

  // Check for filtering.
  if ( $tid === 0) {
    $query->condition('p.tid', 0);
    $cat = t('!Uncategorized', userpoints_translation());
  }
  elseif (is_numeric($tid)) {
    $query->condition('p.tid', $tid);
    $cat = db_query("SELECT name from {taxonomy_term_data} WHERE tid = :tid", array(':tid' => $tid))->fetchField();
  }
  else {
    $cat = t('All');
  }
  drupal_set_title($cat ." ". t("!points", userpoints_translation()));

  if (variable_get(USERPOINTS_REPORT_DISPLAYZERO, 1) == 0 ) {
    // The user would NOT like to see users with zero points.
    $query->condition('p.points', 0, '<>');
  }

  $rows = array();
  foreach ($query->execute() as $data) {
    $rows[] = theme('userpoints_list_users_row', array('row' => $data));
  }
  return theme('userpoints_list_users', array('header' => $header, 'rows' => $rows, 'tid' => $tid));
}

/*
 * Themes the output of users by points page.
 *
 * @return
 *   HTML of the table and a pager
 *
 * @see theme_userpoints_list_users_rows()
 */
function theme_userpoints_list_users($attributes) {
  $header = $attributes['header'];
  $rows = $attributes['rows'];
  $tid = $attributes['tid'];

  // If there is only one category, there is no sense in display the category filter dropdown
  $output = '';
  if (count(userpoints_get_categories()) > 1) {
    $output = drupal_get_form('userpoints_filter_cat_select', 'userpoints/', $tid);
  }
  $output .= theme('table', array('header' => $header, 'rows' => $rows));
  $output .= theme('pager');
  return $output;
}

/**
 * Themes the header of the table on the "user by points" page.
 *
 * @return
 *   An header array used by theme_table() and TableSort.
 */
function theme_userpoints_list_users_header() {
  return array(
    array('data' => t('User'), 'field' => 'u.name'),
    array('data' => t('Category'), 'field' => 't.name'),
    array('data' => t('!Points', userpoints_translation()), 'field' => 'p.points', 'sort' => 'desc'),
  );
}

/*
 * Themes the output of a single row of the "user by points" page
 *
 * @return
 *   Array for a single row, suitable for inclusion with theme_table.
 */
function theme_userpoints_list_users_row($attributes) {
  global $user;

  $row = $attributes['row'];

  if (!$row->cat) {
    $row->cat = t('!Uncategorized', userpoints_translation());
  }

  $details = '';
  if ($user->uid == $row->uid) {
    $details = "&nbsp;&nbsp;" . l(t("(details)"), "myuserpoints");
  }

  return array(
    array('data' => theme('username', array('account' => $row)) . $details),
    array('data' => $row->cat, 'align' => 'right'),
    array('data' => $row->points, 'align' => 'right'),
  );
}

/**
 * Provides a dropdown to filter by category.
 */
function userpoints_filter_cat_select($form, &$form_state, $path, $tid) {
  $current_cat = url($path . $tid);
  $form = array();
  $formname = 'catselect';
  $sql = "SELECT DISTINCT p.tid, t.name
          FROM {userpoints_txn} p
          LEFT JOIN {taxonomy_term_data} t on p.tid = t.tid";
  $cats = userpoints_get_categories();
  $options = array();
  $options[url($path)] = t('Display all');
  foreach ($cats as $key => $value) {
    $options[url($path . $key)] = $value;
  }
  $form['catselect'] = array(
    '#type' => 'select',
    '#name' => $formname,
    '#id' => $formname,
    '#title' => t('Filter by category'),
    '#default_value' => $current_cat,
    '#options' => $options,
    '#multiple' => false,
    '#required' => false,
    '#attributes' => array('onChange' => "top.location.href=document.getElementById('$formname').options[document.getElementById('$formname').selectedIndex].value"),
  );

  return $form;
}

function userpoints_block($op = 'list', $delta = 0, $edit = array()) {
  global $user;

  switch ($op) {
    case 'list':
      $blocks[-1]['info'] = t('User\'s !points', userpoints_translation());
      // Grab a list of the available terms.
      $terms = userpoints_get_categories();
      foreach ($terms as $key => $value) {
        $blocks[$key]['info'] = t("Highest $value !points", userpoints_translation());;
      }

      return $blocks;

    case 'view':
      if ($delta == -1 && (user_access(USERPOINTS_PERM_VIEW) || user_access(USERPOINTS_PERM_VIEW_OWN))) {
          $title = t('@user\'s !points', array_merge(array('@user' => $user->name), userpoints_translation()));;
          if ($user->uid) {
            $points = userpoints_get_current_points($account->uid, variable_get(USERPOINTS_CATEGORY_PROFILE_DISPLAY_TID, 0));
            $show_points = format_plural($points, '!point', '!points', userpoints_translation());
            $content = t('You have %p %c', array('%p' => $points, '%c' => $show_points));
          }
          else {
            $content = t('!Points are visible to logged in users only', userpoints_translation());
          }
        }
      else if (user_access(USERPOINTS_PERM_VIEW)) {
          // $delta is our tid for pulling the points.
          // If 0 we pull 0 or NULL.
          $title = t('Highest Users');
          $num = variable_get('userpoints_block_up_records_'. $delta, 5);
          $sql = 'SELECT p.uid, u.name, p.points
                  FROM {userpoints} p
                  INNER JOIN {users} u USING (uid)';
          if ($delta == 0) {
            $sql .= ' WHERE p.tid = 0 OR p.tid IS NULL ORDER BY p.points DESC';
            $result = db_query_range($sql, 0, $num);
          }
          else {
            $sql .= ' WHERE p.tid = %d ORDER BY p.points DESC';
            $result = db_query_range($sql, $delta, 0, $num);
          }

          while ($data = db_fetch_object($result)) {
            $rows[] =
              array(
                array('data' => theme('username', $data)),
                array('data' => $data->points, 'align' => 'right'));
            }
          $header = array(t('User'), t('!Points', userpoints_translation()));
          $content = theme('table', $header, $rows);
          $content .= '<div class="more-link">'. l(t('more'), 'userpoints/'. $delta, array('attributes' => array('title' => t('All users by !points', userpoints_translation())))) .'</div>';
        }

        $block['subject'] = $title;
        $block['content'] = $content;

        return $block;
    case 'configure':
      $form['up_records'] = array(
        '#type' => 'select',
        '#title' => t('Number of users to display'),
        '#default_value' => variable_get('userpoints_block_up_records_'. $delta, 10),
        '#options' => array(
          1 => 1, 5 => 5, 10 => 10, 15 => 15, 20 => 20,
          30 => 30, 40 => 40, 50 => 50, 60 => 60,
          70 => 70, 80 => 80, 90 => 90, 100 => 100, 200 => 200,
        ),
        '#description' => t('Limit the number of users displayed to this value'),
      );
      return $form;
      break;
    case 'save':
      variable_set('userpoints_block_up_records_'. $delta, $edit['up_records']);
      break;
  }
}
/**
 * returns an array of possible expiry times
 * to the administrative settings page
 */
function expiry_dates() {
  return array(
  NULL     => 'Never',
  3600     => 'One hour',
  86400    => 'One Day',
  604800   => 'One Week',
  1209600  => 'Two Weeks',
  2419200  => 'Four Weeks',
  31536000 => '365 Days',
  );
}

/**
 * Modifies FAPI date setting to timestamp.
 *
 * @return
 *   UNIX timestamp.
 */
function userpoints_date_to_timestamp($date) {
  //This takes the FAPI date form array and returns a timestamp
  if ($date) {
    return mktime(0, 0, 0, $date['month'], $date['day'], $date['year']);
  }
}

/**
 * Finds and expires expired points.
 *
 * Finds all transactions with a expirydate < time() and posts
 * opposite transactions (sum of 0).
 */
function userpoints_expire_transactions() {
  $sql = "SELECT txn_id, uid, points, time_stamp, operation, description
          FROM {userpoints_txn}
          WHERE status = 0 AND expired = 0
          AND (expirydate < :expiry_date AND expirydate != 0)";
  $result = db_query($sql, array(':expiry_date' => REQUEST_TIME));
  foreach ($result as $line) {
    $line->time_stamp = format_date($line->time_stamp, 'custom', 'Y-m-d H:i');
    $description = t(variable_get(USERPOINTS_EXPIRY_DESCRIPTION, NULL),
      array_merge(userpoints_translation(),
      array('!operation' => $line->operation,
        '!description' => $line->description,
        '!txn_id' => $line->txn_id,
        '!date' => $line->time_stamp
        )
      )
    );

    $params = array(
      'points' => -$line->points,
      'uid' => $line->uid,
      'operation' => 'expiry',
      'description' => $description,
      'parent_txn_id' => $line->txn_id,
      'moderate' => false,
      );
    userpoints_userpointsapi($params);
    //Ok we've expired the entry lets update the original entry to set the expired flag
    $params = array(
      'txn_id' => $line->txn_id,
      'expired' => 1,
    );
    userpoints_userpointsapi($params);
  }
}

/**
 * Implements hook_cron().
 */
function userpoints_cron() {
  userpoints_expire_transactions();
}

/**
 * Displays a detailed transaction report for an individual user.
 *
 * @param $uid
 *   User id, defaults to current user.
 */
function userpoints_list_my_userpoints($uid = NULL) {
  $overall_total = 0;
  $unapproved_total = 0;
  $approved_total = 0;

  global $user;

  // User which are displaying points for.
  if ($uid) {
    if ($uid != $user->uid && !user_access(USERPOINTS_PERM_ADMIN)) {
      // If not the same as logged in user.
      drupal_access_denied();
      return;
    }
  }
  else {
    // Default to currently logged in user.
    $uid = $user->uid;
  }
  $point_user = user_load($uid);

  // Check permissions.
  if(!user_access(USERPOINTS_PERM_VIEW) && !user_access(USERPOINTS_PERM_VIEW_OWN)) {
    // User has no access to view points.
    drupal_access_denied();
    return;
  }

  $title = t('!Points for ', userpoints_translation()) . check_plain($point_user->name);
  drupal_set_title($title);

   //Grab all tids for this user.
  $sql = "SELECT p.tid, t.name
    FROM {userpoints_txn} p
    LEFT JOIN {taxonomy_term_data} t on p.tid = t.tid
    WHERE uid = :uid
    GROUP BY p.tid, t.name";
  $results = db_query($sql, array(':uid' => $uid));
  $grand_total = 0;
  foreach ($results as $result) {
    if ($result->name == null) {
      $result->name = t('!Uncategorized', userpoints_translation());
    }
    // Pull the sum from the caching table for resource reason and b/c the.
    $result->total = userpoints_get_current_points($uid, $result->tid);
    $args['subtotals'][$result->tid] = $result;

    // Maintain a grand total.
    $grand_total += $result->total;
  }
  $args['approved_total'] = $grand_total;

  // Grab the unmoderated point total.
  $args['unapproved_total'] = (int)db_query("SELECT SUM(points) FROM {userpoints_txn} WHERE uid = :uid AND status = 1", array(':uid' => $uid))->fetchField();
  $args['overall_total'] = ($args['approved_total'] + $args['unapproved_total']);

  $header = array(
    array('data' => t('!Points', userpoints_translation()), 'field' => 'points'),
    array('data' => t('Approved?'), 'field' => 'status'),
    array('data' => t('Date'), 'field' => 'time_stamp', 'sort' => 'desc'),
    array('data' => t('Operation'), 'field' => 'operation'),
    array('data' => t('Category'), 'field' => 'cat'),
    array('data' => t('Description'), 'field' => 'description'),
  );

  $query = db_select('userpoints_txn', 'p')->extend('PagerDefault')->extend('TableSort')
    ->fields('p', array('txn_id', 'uid', 'time_stamp', 'points', 'operation', 'status', 'entity_type', 'entity_id'))
    ->condition('p.uid', $uid)
    ->orderByHeader($header)
    ->limit(variable_get(USERPOINTS_REPORT_LIMIT, 10));

  $query->leftJoin('taxonomy_term_data', 't', 'p.tid = t.tid');
  $query->addField('t', 'name', 'cat');
  $stati = userpoints_txn_status();
  $num_rows = 0;
  $rows = array();
  foreach ($query->execute() as $row) {
    $num_rows++;
    $status = $stati[$row->status];
    if (!$row->cat) {
      $row->cat = t('!Uncategorized', userpoints_translation());
    }
    if (isset($row->description)) {
      $description = $row->description;
    }
    else {
      $description = t('None');
    }
    $operations = module_invoke_all('userpoints', 'entity_type', $row);
    if (is_array($operations) && isset($operations[0])) {
      $operation = $operations[0];
    }
    else {
      switch ($row->entity_type) {
        case 'node':
          $node = node_load($row->entity_id);
          if ($node) {
            $operation = l($row->operation, 'node/' . $node->nid, array('attributes' => array('title' => $node->title)));
          }
          else {
            $operation = $row->operation;
          }
          break;
        case 'comment':
          if (module_exists('comment')) {
            // We have to load the comment to get the nid for the comment.
            $comment = _comment_load($row->entity_id);
            if ($comment) {
              $operation = l($row->operation, 'node/'. $comment->nid, array('attributes' => array('title' => $comment->subject), 'fragment' => 'comment-'. $comment->cid ));
            }
            else {
              $operation = $row->operation;
            }
          }
          break;
        default:
          $operation = $row->operation;
      }
    }
    $rows[] = array(
      array('data' => $row->points, 'align' => 'center'),
      array('data' => $status, 'align' => 'center'),
      array('data' => format_date($row->time_stamp, 'small'), 'align' => 'center'),
      array('data' => $operation),
      array('data' => $row->cat),
      array('data' => $description),
    );
  	if ($num_rows <= 0) {
    	$rows[] = array(
          array('data' => t('No !Points earned', userpoints_translation()), 'colspan' => 5, 'align' => 'center')
    			);
  	}
  }
  return theme('userpoints_list_my_userpoints', array('args' => $args, 'header' => $header, 'rows' => $rows));
}

/**
 *  Returns the Vocabulary ID (vid) used by userpoints for categorization.
 *
 *  If no vocab exists it will create one.
 */
function userpoints_get_vid() {
	if (!module_exists('taxonomy')) {
    return false;
	}
  // Code lovingly inspired by the image.module w/ code by drewish.
  $vid = variable_get(USERPOINTS_CATEGORY_DEFAULT_VID, '');
  if (empty($vid) || !taxonomy_vocabulary_load($vid)) {
    $sql = "SELECT vid FROM {taxonomy_vocabulary} WHERE module='userpoints'";
    $vid = db_query($sql)->fetchField();
    if (!$vid) {
      drupal_set_message(t("Created Userpoints vocabulary"));
      // No vocabulary exists, we'll create one.
      $vocab = (object)array(
        'name' => t(USERPOINTS_CATEGORY_NAME),
        'description' => t('Automatically created by the userpoints module'),
        'multiple' => '0',
        'required' => '0',
        'hierarchy' => '1',
        'relations' => '0',
        'module' => 'userpoints',
      );
      taxonomy_vocabulary_save($vocab);
      $vid = $vocab->vid;
    }
    variable_set(USERPOINTS_CATEGORY_DEFAULT_VID, $vid);
  }
  if (!is_numeric($vid)) {
    watchdog('userpoints', 'userpoints module was unable to select or create a vocabulary. !Points will be uncategorized', array(), WATCHDOG_ERROR);
  }
  return $vid;
}

/**
 * Returns an array of possible categories, suitable for inclusion in FAPI.
 */
function userpoints_get_categories() {
  // Create the "Uncategorized" category.
  $options = array();
  $options[0] = t('!Uncategorized', userpoints_translation());
  if (module_exists('taxonomy')) {
    $vid = userpoints_get_vid();
    if ($vid) {
      $tree = taxonomy_get_tree($vid, 0, -1, 1);
      foreach ($tree as $term) {
        $options[$term->tid] = $term->name;
      }
    }
  }
  return $options;
}

/**
 * Wrapper function to return the default tid via API call
 */
function userpoints_get_default_tid() {
  return (int)variable_get(USERPOINTS_CATEGORY_DEFAULT_TID, 0);
}

/**
 * Allows my_userpoints to be themeable.
 */
function theme_userpoints_list_my_userpoints($attributes) {
  $args = $attributes['args'];
  $header = $attributes['header'];
  $rows = $attributes['rows'];
  $output  = theme('table', array('header' => $header, 'rows' => $rows));
  $output .= "<p>";
  if (isset($args) && isset($args['subtotals'])) {
    foreach ($args['subtotals'] as $tid => $data) {
      $output .= '<strong>'. $data->name .' '. t('!points Balance', userpoints_translation()) . ':</strong> '. $data->total . '<br />';
    }
  }
  $output .= "</p>";
  $output .= "<p>";
  $output .= '<strong>'. t('Approved !points Balance', userpoints_translation()) .':</strong> '. $args['approved_total'] .'<br />';
  $output .= '<strong>'. t('!Points awaiting moderation', userpoints_translation()) .':</strong> '. $args['unapproved_total'] .'<br />';
  $output .= '<strong>'. t('Net !points Balance', userpoints_translation()) .':</strong> '. $args['overall_total'] .'<br />';
  $output .= "</p>";
  $output .= theme('pager');

  return $output;
}

/**
 *  Implements hook_views_api().
 */
function userpoints_views_api() {
  return array(
    'api' => 2.0,
  );
}
