<?php
// $Id: userpoints_rules.module,v 1.1.2.5 2009-08-11 15:41:39 kbahey Exp $

/**
 * @file
 * Rules integration for the user points module.
 */

/**
 * Rules events -Trigger event when user points awarded.
 */
function userpoints_rules_userpoints($op, $params='') {
  switch ($op) {
  case 'points after':
    rules_invoke_event('userpoints_event_points_awarded', $params['uid'], $params['points']);
    break;
  }
}